language: c

matrix:
  include:
    - osx_image: xcode8.1
      compiler: clang
      os: osx
      env:
        - DISTRO=osx:xcode8.1
        - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig

compiler:
  - clang
  - gcc

os: linux
sudo: required
services: docker
env:
  matrix:
    - DISTRO=fedora:rawhide
    - DISTRO=fedora:latest
    - DISTRO=debian:unstable
    - DISTRO=debian:testing
    - DISTRO=ubuntu:devel

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker create --name=foo -t -v `pwd`:/tmp/build -w /tmp/build $DISTRO /bin/cat
      docker start foo
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        (env | sed -r 's|^(.*)$|-e\n\1|'; echo foo; echo ./.travis.install)
            | xargs -d '\n' docker exec;
    else
        ./.travis.install;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        (env | sed -r 's|^(.*)$|-e\n\1|'; echo foo; echo ./.travis.script)
            | xargs -d '\n' docker exec;
    else
        ./.travis.script;
    fi

after_script:
  - >
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker kill foo
      docker rm foo
    fi
